# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# syntax highlighting
# https://github.com/jneen/rouge/wiki/List-of-supported-languages-and-lexers

# Site settings
title: Beverly Chou @ ITP
email: bevchou@nyu.edu
description: > # this means to ignore newlines until "baseurl:"
  Beverly Chou is a graduate student at NYU ITP, creative technologist and designer. This is her blog of projects at ITP.
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://bevchou.github.io" # the base hostname & protocol for your site
# twitter_username: bevchou
github_username:  bevchou
ig_username: bevchou
linkedin_username: beverlychou


# permalink: /:categories/:title/
permalink: :title/
# pagination: 5

# Build settings
markdown: kramdown
kramdown:
input: GFM
include:
  - "_pages"
  - "assets"
  - "about.md"
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "LICENSE"
  - "README.md"


# Third-party services
# just leave someone empty to disable it
disqus_shortname: bevchou

# used this for post_excerpt at index_page
excerpt_separator: <!--more-->
